### PR TITLE
Change dependency nativescript-telerik-ui to nativescript-pro-ui

### PR DESCRIPTION
**Pull request by beeman**
This seems to fix the error I encountered: 

```
$ tns create drawer-nav --template tns-template-drawer-navigation-ng
Installing  tns-template-drawer-navigation-ng
Progress NativeScript UI Free is licensed under the Telerik End User License Agreement for UI for NativeScript Free: http://www.telerik.com/purchase/license-agreement/ui-for-nativescript-free
Command npm install tns-template-drawer-navigation-ng@3.2.0 --silent --save-exact --save failed with exit code 1
```

### CODE REVIEW

**Comment by manoldonev** [comment]
@beeman I assume the problem you are experiencing is related to a specific issue related to npm@5.4.x -- it is unable to install simultaneously two packages that have `preinstall` scripts. In fact the problem is in one of the dependencies of npm - `npm-lifecycle`.

This problem has been addressed in the latest npm@5.5.1. The reason why switching to pro-ui fixes the problem is the fact that it uses a slightly different installation mechanism (i.e. it's a side effect).

**Comment by ADjenkov** [comment]
@beeman  Thank you for your PR! 
You could just add (in __\App_Resources\iOS\info.plist__):

`<key>NSCalendarsUsageDescription</key>
<string>This application needs to acces your calendar events.</string>`

since Apple requires explicit description when NSCalendar is being used and the `nativescript-pro-ui` contains calendar control. You can lean more about this from the [NativeScriptUI docs](http://docs.telerik.com/devtools/nativescript-ui/getting-started#installing-progress-nativescript-ui)

**Comment by beeman** [comment]
@ADjenkov 

```
You could just add (in \App_Resources\iOS\info.plist):

<key>NSCalendarsUsageDescription</key> <string>This application needs to access your calendar events.</string>

since Apple requires explicit description when NSCalendar is being used and the nativescript-pro-ui contains calendar control. You can learn more about this from the NativeScriptUI docs
```

I'm not sure how this would fix the issue I try to resolve with this PR? 

The error message I get prevents the app from being created in the first place so there is no way to add something to the `info.plist` file.

**Comment by beeman** [comment]
Also, when installing the original package `nativescript-telerik-ui` I get the following message:

> Progress NativeScript UI is now completely free. This package is deprecated, please download the latest version of this package: nativescript-pro-ui

So I guess it makes a lot of sense to update the templates with the newest version. :)

**Comment by ADjenkov** [comment]
Hi @beeman, 

Your PR is absolutely accurate (and completely resolves the issue), but in order to be complete the `info.plist` file should be updated.

Here is a snippet from the latest documentation for `nativescript-pro-ui`: 

> Since iOS 10, Apple requires explicit description when NSCalendar is being used, more precisely when one is trying to access the phone's calendar events. This description is prompted to the user, only when there is an attempt for accessing events, and requires user's confirmation. If you are using UI for NativeScript but never accessing device's calendar your users won't get prompted with this message. In order to submit your application to the AppStore make sure to include a NSCalendarsUsageDescription variable to your info.plist and provide some description, for example "This application needs to acces your calendar events."

**Comment by beeman** [comment]
@ADjenkov thanks for your quick reply and clarification! 

I just updated the PR to include this line in the plist file.

**Comment by ADjenkov** [comment]
Great! 
I'm merging the PR.
@beeman thanks again for your time and effort!

**Comment by beeman** [comment]
Thanks for your help getting it landed @ADjenkov 👍

**Pull request merged**
